"""Data model of a GROMACS topology.

Records refer to each other by name or number (atom types by name, atoms by
their 1-based index in the molecule), so a topology is plain data that can be
edited, copied and written without any cross-references to keep consistent.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, ClassVar, Iterator

from .preprocess import Define
from .specs import MOLECULE_SECTIONS


def _update(record: Any, allowed: frozenset[str], values: dict[str, Any]) -> None:
    unknown = values.keys() - allowed
    if unknown:
        raise KeyError(
            f"Cannot update {sorted(unknown)} of {type(record).__name__}; "
            f"allowed are {sorted(allowed)}."
        )
    for key, value in values.items():
        setattr(record, key, value)


@dataclass
class Defaults:
    nbfunc: int
    comb_rule: int
    gen_pairs: str = "no"
    fudgeLJ: float = 1.0
    fudgeQQ: float = 1.0
    n: int | None = None


@dataclass
class AtomType:
    name: str
    bonded_type: str | None
    atnum: int | None
    mass: float
    charge: float
    ptype: str
    sigma: float
    epsilon: float

    @property
    def btype(self) -> str:
        """The type that bonded parameters are looked up by."""
        return self.bonded_type or self.name

    def update(self, **values: Any) -> None:
        _update(self, frozenset({"sigma", "epsilon"}), values)


@dataclass
class Atom:
    nr: int
    type: str
    resnr: int
    resname: str
    name: str
    cgnr: int
    charge: float | str
    mass: float | str
    type_b: str | None = None
    charge_b: float | str | None = None
    mass_b: float | str | None = None

    def update(self, **values: Any) -> None:
        _update(self, frozenset({"charge", "charge_b"}), values)


@dataclass
class Interaction:
    """One line of a molecular interaction directive.

    ``atoms`` are 1-based atom numbers of the molecule. ``params`` maps
    parameter names to numbers (or to macro names); B-state values carry a
    ``_b`` suffix. An empty ``params`` means the parameters are generated by
    GROMACS (pairs with ``gen-pairs = yes``) or that the function has none.
    """

    section: str
    atoms: tuple[int, ...]
    func: int
    params: dict[str, float | int | str] = field(default_factory=dict)

    def update(self, **values: Any) -> None:
        unknown = values.keys() - self.params.keys()
        if unknown:
            raise KeyError(
                f"Cannot add new parameter(s) {sorted(unknown)}; "
                f"allowed keys are {sorted(self.params)}."
            )
        self.params.update(values)


@dataclass
class TypeEntry:
    """One line of a parameter table such as ``[ bondtypes ]``."""

    section: str
    types: tuple[str, ...]
    func: int
    params: dict[str, float | int | str] = field(default_factory=dict)

    def update(self, **values: Any) -> None:
        unknown = values.keys() - self.params.keys()
        if unknown:
            raise KeyError(
                f"Cannot add new parameter(s) {sorted(unknown)}; "
                f"allowed keys are {sorted(self.params)}."
            )
        self.params.update(values)


@dataclass
class CmapType:
    """A CMAP correction grid for five consecutive bonded types."""

    types: tuple[str, ...]
    func: int
    nx: int
    ny: int
    values: list[float]


@dataclass
class MoleculeType:
    name: str
    nrexcl: int
    atoms: list[Atom] = field(default_factory=list)
    interactions: dict[str, list[Interaction]] = field(default_factory=dict)
    exclusions: list[tuple[int, ...]] = field(default_factory=list)

    SECTIONS: ClassVar[tuple[str, ...]] = MOLECULE_SECTIONS

    def __getattr__(self, name: str) -> list[Interaction]:
        # ``mol.bonds``, ``mol.dihedrals``, ... are the lists in ``interactions``.
        if name in MoleculeType.SECTIONS and name != "interactions":
            return self.interactions.setdefault(name, [])
        raise AttributeError(name)

    def __repr__(self) -> str:
        return f"<MoleculeType name={self.name} nrexcl={self.nrexcl}>"


class Topology:
    """A GROMACS topology read from a file with its includes resolved.

    Conditional blocks are evaluated against ``defines`` (like ``define = -DX``
    in an mdp file) and the ``#define`` lines of the files themselves, so only
    the active branches are kept.
    """

    def __init__(
        self,
        source: str | Path | None = None,
        *,
        defines: dict[str, Any] | None = None,
        include_dirs: list[str | Path] = (),
    ) -> None:
        self.source: Path | None = None
        self.defaults: Defaults | None = None
        self.defines: list[Define] = []
        self.atomtypes: list[AtomType] = []
        self.types: dict[str, list[TypeEntry]] = {}
        self.cmaptypes: list[CmapType] = []
        self.moleculetypes: list[MoleculeType] = []
        self.system: str = ""
        self.molecules: list[tuple[MoleculeType, int]] = []
        self.intermolecular: dict[str, list[Interaction]] = {}
        # Macros passed by the caller that were not defined in the files.
        self.external_defines: dict[str, Define] = {}

        if source is not None:
            from .parser import read_topology

            self.source = Path(source).resolve()
            read_topology(self, defines, [Path(d) for d in include_dirs])

    def moleculetype(self, name: str) -> MoleculeType:
        """The molecule type called ``name`` (case-insensitive, like GROMACS)."""
        for moleculetype in self.moleculetypes:
            if moleculetype.name.casefold() == name.casefold():
                return moleculetype
        raise KeyError(f"Molecule type '{name}' not found in {self.source}.")

    def atomtype(self, name: str) -> AtomType:
        for atomtype in self.atomtypes:
            if atomtype.name == name:
                return atomtype
        raise KeyError(f"Atom type '{name}' not found in {self.source}.")

    @property
    def residues(self) -> list[MoleculeType]:
        """The molecule of every copy in ``[ molecules ]``, in order."""
        return [mol for mol, count in self.molecules for _ in range(count)]

    @property
    def atoms(self) -> list[Atom]:
        """All atoms of the system, in coordinate-file order."""
        return list(self._iter_atoms())

    def _iter_atoms(self) -> Iterator[Atom]:
        for mol, count in self.molecules:
            for _ in range(count):
                yield from mol.atoms

    def write(self, fn: str | Path, overwrite: bool = False) -> None:
        from .writer import write_topology

        write_topology(self, Path(fn), overwrite=overwrite)

    def __repr__(self) -> str:
        return (
            f"<Topology system='{self.system}' "
            f"moleculetypes={len(self.moleculetypes)} "
            f"molecules={sum(count for _, count in self.molecules)} "
            f"atoms={len(self.atoms)}>"
        )
