"""Reading and writing of GROMACS topologies."""

import warnings
from pathlib import Path

import pytest

from gmxtopology import Topology, TopologyError, drop_vsites

ROOT = Path(__file__).resolve().parents[1]
GROMACS_FIXTURES = ROOT / "tests/fixtures/gromacs-v2026.2"
PARMED_FIXTURES = ROOT / "tests/fixtures/parmed-96ec61a"
PROSECCO_FIXTURES = ROOT / "tests/fixtures/prosECCo75-e4831a4"

HEADER = """
[ defaults ]
1 2 no 1.0 1.0

[ atomtypes ]
; name  bonded  at.num  mass   charge ptype sigma epsilon
A   12.011  0.0  A  0.34  0.10
B   B_bt  6  1.008  0.0  A  0.25  0.05
C   12  14.007  -0.3  A  0.32  0.15
"""

FOOTER = """
[ system ]
test

[ molecules ]
MOL 1
"""

ATOMS = """
[ moleculetype ]
MOL 3

[ atoms ]
1 A 1 MOL A1 1 0.0 12.011
2 B 1 MOL B1 2 0.1 1.008
3 C 1 MOL C1 3 -0.1 14.007
4 A 1 MOL A2 4 0.0 12.011
"""


def read(tmp_path: Path, text: str, **kwargs) -> Topology:
    path = tmp_path / "in.top"
    path.write_text(text)
    return Topology(path, **kwargs)


def roundtrip(tmp_path: Path, top: Topology) -> Topology:
    out = tmp_path / "out.top"
    top.write(out)
    return Topology(out)


def interactions(top: Topology) -> dict:
    return {
        mol.name: {
            section: [(i.atoms, i.func, dict(i.params)) for i in items]
            for section, items in mol.interactions.items()
            if items
        }
        for mol in {m.name: m for m, _ in top.molecules}.values()
    }


# -- preprocessing ---------------------------------------------------------


def test_conditionals_are_evaluated_against_defines(tmp_path):
    text = (
        HEADER
        + """
#ifdef HEAVY
#define MASS 12.0
#else
#define MASS 1.0
#endif
"""
        + ATOMS
        + """
[ bonds ]
1 2 1 0.1 1000
#ifndef NOBOND
2 3 1 0.2 MASS
#endif
"""
        + FOOTER
    )

    top = read(tmp_path, text)
    assert [d.directive for d in top.defines] == ["MASS"]
    assert top.defines[0].argument == "1.0"
    assert [b.params["kb"] for b in top.moleculetype("MOL").bonds] == [1000.0, "MASS"]

    top = read(tmp_path, text, defines={"HEAVY": None, "NOBOND": None})
    assert top.defines[0].argument == "12.0"
    assert len(top.moleculetype("MOL").bonds) == 1


def test_include_search_continuation_and_inactive_missing_include(tmp_path):
    (tmp_path / "ff").mkdir()
    (tmp_path / "ff/forcefield.itp").write_text(HEADER)
    (tmp_path / "extra").mkdir()
    (tmp_path / "extra/mol.itp").write_text(ATOMS)
    text = (
        """
#include "ff/forcefield.itp"
#ifdef NEVER
#include "missing.itp"
#endif
#include "mol.itp"
[ bonds ]
1 2 1 \\
   0.1 1000
"""
        + FOOTER
    )

    top = read(tmp_path, text, include_dirs=[tmp_path / "extra"])
    assert top.moleculetype("MOL").bonds[0].params == {"b0": 0.1, "kb": 1000.0}

    with pytest.raises(FileNotFoundError, match="missing.itp"):
        read(tmp_path, text, defines={"NEVER": None}, include_dirs=[tmp_path / "extra"])


def test_errors_carry_file_and_line(tmp_path):
    text = HEADER + ATOMS + "[ bonds ]\n1 2 1 0.1 abc\n" + FOOTER
    with pytest.raises(TopologyError, match=r"in\.top:\d+"):
        read(tmp_path, text)


@pytest.mark.parametrize(
    "bad, message",
    [
        ("#ifdef X\n" + HEADER, "Unclosed conditional"),
        ("#if X\n#endif\n" + HEADER, "Unsupported preprocessor directive"),
        ("#endif\n" + HEADER, "unmatched #endif"),
    ],
)
def test_invalid_preprocessor_input_is_rejected(tmp_path, bad, message):
    with pytest.raises(TopologyError, match=message):
        read(tmp_path, bad + ATOMS + FOOTER)


# -- parameter tables ------------------------------------------------------


def test_atomtype_layouts(tmp_path):
    top = read(tmp_path, HEADER + ATOMS + FOOTER)
    a, b, c = (top.atomtype(name) for name in "ABC")
    assert (a.bonded_type, a.atnum) == (None, None)
    assert (b.bonded_type, b.atnum) == ("B_bt", 6)
    assert (c.bonded_type, c.atnum) == (None, 12)
    assert (a.btype, b.btype, c.btype) == ("A", "B_bt", "C")


def test_bonded_parameters_are_looked_up_by_bonded_type(tmp_path):
    text = (
        HEADER
        + """
[ bondtypes ]
A B_bt 1 0.15 2000
[ constrainttypes ]
A C 1 0.12
"""
        + ATOMS
        + """
[ bonds ]
1 2
[ constraints ]
1 3 1
"""
        + FOOTER
    )
    mol = read(tmp_path, text).moleculetype("MOL")
    assert mol.bonds[0].func == 1
    assert mol.bonds[0].params == {"b0": 0.15, "kb": 2000.0}
    assert mol.constraints[0].params == {"b0": 0.12}


def test_pairtypes_take_precedence_over_gen_pairs(tmp_path):
    text = (
        HEADER.replace("1 2 no 1.0 1.0", "1 2 yes 0.5 0.8333")
        + """
[ pairtypes ]
A C 1 0.3 0.4
"""
        + ATOMS
        + """
[ pairs ]
1 3 1
2 4 1
"""
        + FOOTER
    )
    top = read(tmp_path, text)
    pairs = top.moleculetype("MOL").pairs
    assert pairs[0].params == {"sigma": 0.3, "epsilon": 0.4}
    assert pairs[1].params == {}  # generated by GROMACS from the atom types
    assert interactions(roundtrip(tmp_path, top)) == interactions(top)


def test_missing_parameters_are_an_error_with_context(tmp_path):
    text = HEADER + ATOMS + "[ angles ]\n1 2 3 1\n" + FOOTER
    with pytest.raises(TopologyError, match=r"angletypes.*A1.*MOL.*in\.top:\d+"):
        read(tmp_path, text)


def test_dihedraltypes_two_type_forms_and_wildcards(tmp_path):
    text = (
        HEADER
        + """
[ dihedraltypes ]
B_bt C 3 1 2 3 4 5 6
A A 2 10.0 20.0
X B_bt C X 9 0.0 1.0 1
"""
        + ATOMS
        + """
[ dihedrals ]
1 2 3 4 3
1 2 3 4 2
4 3 2 1 9
"""
        + FOOTER
    )
    # atom types A B_bt C A: "j k" is the central pair, impropers use "i l"
    rb, improper, wild = read(tmp_path, text).moleculetype("MOL").dihedrals
    assert rb.params["C0"] == 1.0 and rb.params["C5"] == 6.0
    assert improper.params == {"xi0": 10.0, "kxi": 20.0}
    assert wild.params["kphi"] == 1.0  # matched in reverse orientation


def test_exact_dihedraltype_beats_wildcard(tmp_path):
    text = (
        HEADER
        + """
[ dihedraltypes ]
X B_bt C X 9 0.0 1.0 1
A B_bt C A 9 0.0 5.0 2
"""
        + ATOMS
        + "[ dihedrals ]\n1 2 3 4 9\n"
        + FOOTER
    )
    dihedrals = read(tmp_path, text).moleculetype("MOL").dihedrals
    assert [d.params["kphi"] for d in dihedrals] == [5.0]


def test_func9_adjacent_lines_with_equal_multiplicity_are_all_kept(tmp_path):
    text = (
        HEADER
        + """
[ dihedraltypes ]
A B_bt C A 9 0.0 5.0 2
A B_bt C A 9 180.0 6.0 2
"""
        + ATOMS
        + "[ dihedrals ]\n1 2 3 4 9\n"
        + FOOTER
    )
    dihedrals = read(tmp_path, text).moleculetype("MOL").dihedrals
    assert [(d.params["phi_s"], d.params["kphi"]) for d in dihedrals] == [
        (0.0, 5.0),
        (180.0, 6.0),
    ]


def test_repeated_non_func9_type_replaces_the_earlier_one(tmp_path):
    text = (
        HEADER
        + """
[ bondtypes ]
A B_bt 1 0.1 100
A B_bt 1 0.2 200
"""
        + ATOMS
        + "[ bonds ]\n1 2\n"
        + FOOTER
    )
    assert read(tmp_path, text).moleculetype("MOL").bonds[0].params["kb"] == 200.0


# -- molecules -------------------------------------------------------------


def test_molecules_keep_order_and_repeated_names(tmp_path):
    text = (
        HEADER
        + ATOMS
        + """
[ moleculetype ]
ION 1
[ atoms ]
1 B 1 ION B1 1 1.0 1.008

[ system ]
test
[ molecules ]
mol 2
ION 5
MOL 3
"""
    )
    top = read(tmp_path, text)
    assert [(m.name, n) for m, n in top.molecules] == [
        ("MOL", 2),
        ("ION", 5),
        ("MOL", 3),
    ]
    assert len(top.atoms) == 2 * 4 + 5 + 3 * 4
    again = roundtrip(tmp_path, top)
    assert [(m.name, n) for m, n in again.molecules] == [
        ("MOL", 2),
        ("ION", 5),
        ("MOL", 3),
    ]


def test_residue_names_and_atom_defaults_survive(tmp_path):
    text = (
        HEADER
        + """
[ moleculetype ]
PEP 3
[ atoms ]
1 A 1 ALA A1 1 0.5
2 B 2 GLY B1 1
"""
        + FOOTER.replace("MOL 1", "PEP 1")
    )
    top = roundtrip(tmp_path, read(tmp_path, text))
    atoms = top.moleculetype("PEP").atoms
    assert [a.resname for a in atoms] == ["ALA", "GLY"]
    assert [a.charge for a in atoms] == [0.5, 0.0]  # omitted: atom type charge
    assert [a.mass for a in atoms] == [12.011, 1.008]  # omitted: atom type mass


def test_atoms_must_be_numbered_consecutively(tmp_path):
    text = (
        HEADER
        + "[ moleculetype ]\nMOL 3\n[ atoms ]\n1 A 1 MOL A1 1 0 1\n3 A 1 MOL A2 1 0 1\n"
    )
    with pytest.raises(TopologyError, match="numbered consecutively"):
        read(tmp_path, text + FOOTER)


def test_parameter_tables_after_a_molecule_are_rejected(tmp_path):
    text = HEADER + ATOMS + "[ bondtypes ]\nA B_bt 1 0.1 100\n" + FOOTER
    with pytest.raises(TopologyError, match="parameter tables must come first"):
        read(tmp_path, text)


def test_connection_bond_needs_no_parameters(tmp_path):
    text = HEADER + ATOMS + "[ bonds ]\n1 2 5\n" + FOOTER
    bond = read(tmp_path, text).moleculetype("MOL").bonds[0]
    assert (bond.func, bond.params) == (5, {})


def test_b_state_parameters_and_atoms(tmp_path):
    text = (
        HEADER
        + """
[ moleculetype ]
MOL 3
[ atoms ]
1 A 1 MOL A1 1 0.0 12.011 B 0.1 1.008
2 B 1 MOL B1 2 0.1 1.008
[ bonds ]
1 2 1 0.1 1000 0.2 2000
"""
        + FOOTER
    )
    top = roundtrip(tmp_path, read(tmp_path, text))
    mol = top.moleculetype("MOL")
    assert mol.atoms[0].type_b == "B" and mol.atoms[0].charge_b == 0.1
    assert mol.bonds[0].params == {"b0": 0.1, "kb": 1000.0, "b0_b": 0.2, "kb_b": 2000.0}


def test_intermolecular_interactions_are_written_last(tmp_path):
    text = (
        HEADER
        + ATOMS
        + FOOTER
        + """
[ intermolecular_interactions ]
[ bonds ]
1 5 6 0.3 100
"""
    )
    top = roundtrip(tmp_path, read(tmp_path, text))
    assert top.intermolecular["bonds"][0].atoms == (1, 5)
    assert top.intermolecular["bonds"][0].func == 6


# -- macros ----------------------------------------------------------------


def test_macros_stay_editable_and_are_defined_in_the_output(tmp_path):
    text = (
        """
#define KB 1000
#define GB_X 0.1 2000
"""
        + HEADER
        + ATOMS
        + """
[ bonds ]
1 2 1 0.1 KB
2 3 1 GB_X
"""
        + FOOTER
    )
    top = read(tmp_path, text)
    bonds = top.moleculetype("MOL").bonds
    assert bonds[0].params["kb"] == "KB"  # symbolic, follows the #define
    assert bonds[1].params == {"b0": 0.1, "kb": 2000.0}  # one macro, two values

    top.defines[0].update(argument=1500)
    out = tmp_path / "out.top"
    top.write(out)
    text = out.read_text()
    assert "#define KB 1500" in text
    assert "GB_X" not in text
    assert Topology(out).moleculetype("MOL").bonds[0].params["kb"] == "KB"


# -- CMAP ------------------------------------------------------------------


def test_only_used_cmap_grids_are_written_and_cmap_is_renumbered(tmp_path):
    grid = " ".join(str(float(i)) for i in range(4))
    text = (
        HEADER
        + f"""
[ cmaptypes ]
A B_bt C A B_bt 1 2 2 \\
{grid}
C C C C C 1 2 2 {grid}
"""
        + """
[ moleculetype ]
MOL 3
[ atoms ]
1 B 1 MOL V1 1 0 1.008
2 A 1 MOL A1 1 0 12.011
3 B 1 MOL B1 1 0 1.008
4 C 1 MOL C1 1 0 14.007
5 A 1 MOL A2 1 0 12.011
6 B 1 MOL B2 1 0 1.008
[ cmap ]
2 3 4 5 6 1
[ virtual_sites1 ]
1 2 1
"""
        + FOOTER
    )
    top = read(tmp_path, text)
    assert len(top.cmaptypes) == 2

    drop_vsites(top.moleculetype("MOL"))
    assert top.moleculetype("MOL").cmap[0].atoms == (1, 2, 3, 4, 5)

    out = roundtrip(tmp_path, top)
    assert [c.types for c in out.cmaptypes] == [("A", "B_bt", "C", "A", "B_bt")]
    assert out.cmaptypes[0].values == [0.0, 1.0, 2.0, 3.0]
    assert out.moleculetype("MOL").cmap[0].atoms == (1, 2, 3, 4, 5)


def test_prosecco_cmap_fixture_writes_only_the_used_grid(tmp_path):
    top = Topology(PROSECCO_FIXTURES / "topol-cmap.top")
    assert len(top.cmaptypes) == 12
    out = roundtrip(tmp_path, top)
    assert len(out.cmaptypes) == 1
    assert out.cmaptypes[0].types == ("C", "NH1", "CT1", "C", "NH1")
    assert out.cmaptypes[0].values == top.cmaptypes[0].values
    assert (
        "cmaptypes"
        not in (tmp_path / "out.top").read_text().split("[ moleculetype ]")[1]
    )


# -- writing only what is relevant -------------------------------------------


def test_written_topology_contains_only_the_used_parts(tmp_path):
    text = (
        HEADER
        + """
[ nonbond_params ]
A B 1 0.5 0.6
A C 1 0.7 0.8
[ bondtypes ]
A B_bt 1 0.1 100
"""
        + ATOMS
        + "[ bonds ]\n1 2\n"
        + """
[ moleculetype ]
UNUSED 3
[ atoms ]
1 C 1 UNUSED C1 1 0 14.007
"""
        + FOOTER.replace("MOL 1", "MOL 2")
    )
    top = read(tmp_path, text)
    top.atomtypes.append(
        type(top.atomtypes[0])("Z", None, None, 1.0, 0.0, "A", 0.1, 0.1)
    )
    out = roundtrip(tmp_path, top)
    assert [a.name for a in out.atomtypes] == ["A", "B", "C"]
    assert [m.name for m in out.moleculetypes] == ["MOL"]
    assert "bondtypes" not in (tmp_path / "out.top").read_text()
    assert len(out.types["nonbond_params"]) == 2
    assert out.moleculetype("MOL").bonds[0].params == {"b0": 0.1, "kb": 100.0}


def test_write_refuses_to_overwrite(tmp_path):
    top = read(tmp_path, HEADER + ATOMS + FOOTER)
    out = tmp_path / "out.top"
    top.write(out)
    with pytest.raises(FileExistsError):
        top.write(out)
    top.write(out, overwrite=True)


def test_interaction_update_is_restricted_to_existing_parameters(tmp_path):
    top = read(tmp_path, HEADER + ATOMS + "[ bonds ]\n1 2 1 0.1 100\n" + FOOTER)
    bond = top.moleculetype("MOL").bonds[0]
    bond.update(kb=5.0)
    assert bond.params["kb"] == 5.0
    with pytest.raises(KeyError):
        bond.update(new=1.0)
    with pytest.raises(KeyError):
        top.atoms[0].update(mass=2.0)
    top.atomtype("A").update(sigma=0.5)
    assert top.atomtype("A").sigma == 0.5


# -- fixtures --------------------------------------------------------------


@pytest.mark.parametrize(
    "path, atoms",
    [
        (GROMACS_FIXTURES / "topol-spce.top", 3),
        (GROMACS_FIXTURES / "topol-tip3p.top", 3),
        (GROMACS_FIXTURES / "topol-tip4p.top", 4),
        (GROMACS_FIXTURES / "topol-urea.top", 8),
        (PARMED_FIXTURES / "01.1water/topol.top", 3),
        (PARMED_FIXTURES / "02.6water/topol.top", 24),
        (PARMED_FIXTURES / "03.AlaGlu/topol.top", 49),
        (PARMED_FIXTURES / "07.DHFR-Liquid-NoPBC/topol.top", 23569),
        (
            PARMED_FIXTURES
            / "11a.Toluene-Cyclohexane_conversion/toluene_cyclohexane_10_500_parmed.top",
            9150,
        ),
        (PARMED_FIXTURES / "12.DPPC/topol.top", 1132),
        (PARMED_FIXTURES / "12A.DPPC_Amber/topol.top", 1132),
        (PROSECCO_FIXTURES / "topol-popc.top", 134),
        (PROSECCO_FIXTURES / "topol-cmap.top", 5),
    ],
    ids=lambda p: p.parent.name + "/" + p.name if isinstance(p, Path) else str(p),
)
def test_fixture_topologies_roundtrip(tmp_path, path, atoms):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        top = Topology(path)
    assert len(top.atoms) == atoms
    again = roundtrip(tmp_path, top)
    assert len(again.atoms) == atoms
    assert interactions(again) == interactions(top)
    assert [(m.name, n) for m, n in again.molecules] == [
        (m.name, n) for m, n in top.molecules
    ]


def test_tip4p_virtual_sites_can_be_removed(tmp_path):
    top = Topology(GROMACS_FIXTURES / "topol-tip4p.top")
    mol = top.moleculetype("SOL")
    assert len(mol.virtual_sites3) == 1
    drop_vsites(mol)
    assert len(mol.atoms) == 3
    assert not mol.virtual_sites3
    assert all(nr <= 3 for group in mol.exclusions for nr in group)
    assert len(roundtrip(tmp_path, top).atoms) == 3


def test_prosecco_popc_interactions():
    top = Topology(PROSECCO_FIXTURES / "topol-popc.top")
    mol = top.moleculetype("POPC_s")
    assert (len(mol.atoms), len(mol.bonds), len(mol.pairs)) == (134, 133, 356)
    assert (len(mol.angles), len(mol.dihedrals)) == (256, 467)


def test_example_topologies_parse():
    top = Topology(ROOT / "examples/topol.top")
    assert [(m.name, n) for m, n in top.molecules] == [("POPC", 128), ("SOL", 8881)]
    cond = Topology(ROOT / "examples/topol_new.top", defines={"mod": None})
    assert [d.directive for d in cond.defines] == ["vsa", "charge"]
